### ISSUE TITLE
Bootcamp Checklist

### ISSUE THREAD

**Issue by hillc5** [darrenkovalchik/slalom-ember-bootcamp-example#2]
We are going to divide the talk *roughly* into the following Major Sections:
* Routes & templates 
* Components
* Actions
* Services
* Mixins/Utils
* Tests

The following will be a checklist that we can use/grow to help us organize the various components of the bootcamp.  **So for each Major Section above:**

- [ ] Flesh out the sub-sections that will be included
- [ ] Divise the branch state (start and finish) for each major section
  * Note: Branches should be clean starting places for each Major Section that encompasses all (or the majority of) the work done in the previous Major Section
- [ ] Divise the beginning and end application state for each Major Section
- [ ] Create an issue that will track the above application development work for each Major Section
  * Every thing that gets added to the application for any Major Section should be functional and should be used to demonstrate the sub-section that is currently being illustrated

**Comment by hillc5** [comment]
@darrenkovalchik Image from our initial discussion of bootcamp layout:

![emberbootcamp notes](https://cloud.githubusercontent.com/assets/3486065/16172908/4eee0270-3547-11e6-967f-4071de046047.jpg)
